print("Take one Deodorant for yourself or stay smelly.")
# Deodorant 1
# Deodorant 2
# Deodorant 3
# Deodorant 4
# Deodorant 5
# Deodorant 6
# Deodorant 7
# Deodorant 8
# Deodorant 9
# Deodorant 10
# Deodorant 12
# Deodorant 13
# Deodorant 14
# Deodorant 15
# Deodorant 16
# Deodorant 17
# Deodorant 18
# Deodorant 19
# Deodorant 20
